# Generated by Django 5.1.15 on 2026-07-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Boondhu', help_text='Site name displayed in the admin header', max_length=100)),
                ('tagline', models.CharField(blank=True, default='Always Everywhere', help_text='Tagline shown in the admin footer', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text='Main site logo (recommended: 200×200px PNG with transparent background)', null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, help_text='Favicon icon (recommended: 32×32px or 64×64px PNG)', null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
