# Generated by Django 5.1.15 on 2026-07-17 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryParcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('sender_name', models.CharField(max_length=100)),
                ('sender_phone', models.CharField(max_length=20)),
                ('pickup_address', models.TextField(help_text='Pickup location')),
                ('pickup_area', models.CharField(blank=True, max_length=100)),
                ('delivery_address', models.TextField(help_text='Delivery location')),
                ('delivery_area', models.CharField(blank=True, max_length=100)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('parcel_type', models.CharField(choices=[('document', 'Document'), ('small_parcel', 'Small Parcel'), ('medium_parcel', 'Medium Parcel'), ('large_parcel', 'Large Parcel'), ('fragile', 'Fragile Item'), ('food', 'Food Delivery')], default='small_parcel', max_length=20)),
                ('weight', models.CharField(choices=[('up_to_1kg', 'Up to 1 kg'), ('1_to_5kg', '1-5 kg'), ('5_to_10kg', '5-10 kg'), ('above_10kg', 'Above 10 kg')], default='up_to_1kg', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Parcel description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='delivery/parcels/')),
                ('price', models.DecimalField(decimal_places=2, help_text='Delivery fee in BDT (৳)', max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20)),
                ('eta', models.CharField(default='Calculating...', help_text='Estimated time of arrival', max_length=50)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Delivery instructions')),
                ('rider', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'rider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_parcels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delivery Parcel',
                'verbose_name_plural': 'Delivery Parcels',
                'ordering': ['-created_at'],
            },
        ),
    ]
