# Generated by Django 5.1.15 on 2026-07-17 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Meal Category',
                'verbose_name_plural': 'Meal Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating (0.0 - 5.0)', max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0, help_text='Number of ratings received')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='kitchen/logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='kitchen/covers/')),
                ('area', models.CharField(blank=True, help_text='Service area/locality', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('opening_time', models.TimeField(default='08:00')),
                ('closing_time', models.TimeField(default='22:00')),
                ('minimum_order', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount in BDT', max_digits=8)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=30, help_text='Delivery fee in BDT', max_digits=8)),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'kitchen_owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kitchen',
                'verbose_name_plural': 'Kitchens',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating (0.0 - 5.0)', max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0, help_text='Number of ratings received')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in BDT (৳)', max_digits=8)),
                ('description', models.TextField(blank=True)),
                ('preparation_time', models.CharField(default='30 mins', help_text='Estimated preparation time (e.g., 30 mins)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='kitchen/meals/')),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_vegetarian', models.BooleanField(default=False)),
                ('is_spicy', models.BooleanField(default=False)),
                ('kitchen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='kitchen.kitchen')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meals', to='kitchen.mealcategory')),
            ],
            options={
                'verbose_name': 'Meal',
                'verbose_name_plural': 'Meals',
                'ordering': ['-is_featured', '-rating', 'name'],
            },
        ),
    ]
