# Generated by Django 5.1.15 on 2026-07-17 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon name (e.g., shopping_basket, local_pharmacy)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='store/categories/')),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, help_text='Average rating (0.0 - 5.0)', max_digits=3)),
                ('rating_count', models.PositiveIntegerField(default=0, help_text='Number of ratings received')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in BDT (৳)', max_digits=10)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Discounted price in BDT (৳). Leave blank if no discount.', max_digits=10, null=True)),
                ('unit', models.CharField(default='piece', help_text='Unit of measurement (e.g., kg, piece, pack, bottle)', max_length=20)),
                ('description', models.TextField(default='Premium quality product sourced directly from the best producers.')),
                ('stock_quantity', models.PositiveIntegerField(default=0, help_text='Available stock quantity')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Show in featured/trending section')),
                ('vendor', models.ForeignKey(blank=True, help_text='Product vendor/seller', limit_choices_to={'user_type': 'vendor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_products', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store.productcategory')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='store/products/')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Mark as the primary/thumbnail image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
    ]
